contact_links:
  - name: â” Questions / Aide
    url: https://discord.gg/XyNerQ6ZXX
    about: Veuillez utiliser le serveur support discord pour obtenir de l'aide et poser des questions, ne dÃ©marrez pas d'issue.
  - name: ğŸ“ƒ Guide Discord.js
    url: https://discordjs.guide/
    about: Le guide officiel de discord.js